### ISSUE TITLE
Add project room information/policy

### ISSUE THREAD

**Issue by FFAxKenny** [IEEE-UH-Manoa/eesab-website#15]
The website in it's current form doesn't contain any information about the EE student project room; this should be included as soon as possible, since the room has been open for quite a while. 

Might be prudent to replace the 'archive' tab and add a 'resources' section tab on the top or something.

**Comment by FFAxKenny** [comment]
@kaleonorman: any thoughts on this? I'm not sure if you guys discussed anything extra in the meeting - I'm thinking we should just throw up Dr. Shiroma's original email to the x96 students and the documents attached in that email.

**Comment by felixjos** [comment]
I found the e-mail in my archives, I'll go ahead and make a new branch to preview the x96 holmes 450 room.

**Comment by FFAxKenny** [comment]
@felixjos: sweet, thanks.

**Comment by felixjos** [comment]
Added a page with policy and pdfs for usage
