### ISSUE TITLE
News page formatting is difficult to parse

### ISSUE THREAD

**Issue by talexand** [IEEE-UH-Manoa/eesab-website#7]
Article headlines are larger than news link headlines, making it difficult to visually separate. There should be another separator like `<hr>` to break them up, also.

**Comment by felixjos** [comment]
Updated news section.  Take a look on the dev branch.  I also decided to add a summary section.  I noticed that if we just do a truncation there are possible formatting errors that tweak the look.  The summary section will also make it easier for students to understand what the update is if we word it nicely.

**Comment by felixjos** [comment]
Has been updated to be more easily viewable

**Comment by talexand** [comment]
looks awesome!
