### ISSUE TITLE
Anonymous Comment Form Doesn't Work

### ISSUE THREAD

**Issue by FFAxKenny** [IEEE-UH-Manoa/eesab-website#8]
The anonymous comment form still doesn't work (can be found on this page: http://www-ee.eng.hawaii.edu/~eesab/contact/). 

I believe we have to confirm our email with the form provider still.

**Comment by FFAxKenny** [comment]
bump @felixjos @kaleonorman

**Comment by FFAxKenny** [comment]
This is particularly important; students can't make any comments if there is no venue for them to do so... I'd like to advertise this at the new IEEE general meeting (and continue to do so to provide our students with a voice).

**Comment by kaleonorman** [comment]
We'll have to migrate it to Formspree. Does anyone know how to do this?

**Comment by FFAxKenny** [comment]
Looks like we need to find another alternative: 

http://blog.brace.io/2014/11/17/squarespace/
"""
What this means for Brace is that, as of today, we are no longer enrolling new users. Existing users can continue to use our service until Jan 19, 2015. At that time all Brace sites, including redirects will be disabled. For our free users, you will receive a coupon worth three months of free service on Site44. For our paying customers, you will receive a full refund for your last subscription period. You’ll also receive the Site44 coupon and, in addition, Squarespace is offering a full year of service on their Unlimited plan for free. Look for a follow-up email with more details and instructions.

As for our free tools for forms, charts and data, Squarespace has agreed to release these tools back to the developer community as open source projects. Please watch out for announcements with more detail on those products’ websites (forms.brace.io, charts.brace.io and data.brace.io).
"""

**Comment by FFAxKenny** [comment]
Is there anything wrong with just creating a google form that users can submit comments to? We can set the form to notify the SAB email address when theres a new response..... 

I can't remember what we discussed earlier but this may be the easiest way to get something on there...

**Comment by talexand** [comment]
At least as a stopgap measure, a google form is not unreasonable. We should consider that whoever is the "GApps administrator" or other responsible individual at UH will probably have access though, and move to something different afterward.

**Comment by FFAxKenny** [comment]
I can't recall - what was the original benefit of the previous system we were proposed to use? Was the concern that we needed to verify that the comments were from an actual student?

Otherwise, we could just create a form outside of the Google@UH domain which would circumvent the UH GApps administrator having access to the form.

**Comment by talexand** [comment]
The main thing we were focused on was ensuring the comments were anonymous and more or less directly reached the SAB.

**Comment by felixjos** [comment]
I've been looking at a couple of possibilities, I'll try them out then create some branches to test.

**Comment by FFAxKenny** [comment]
Cool, thanks - as long as we have something before the next IEEE meeting (Feb 18).
